# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreatingprofile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_creatingprofile(self):
    self.driver.get("https://tobeto.com/")
    self.driver.set_window_size(1680, 953)
    self.driver.find_element(By.LINK_TEXT, "Giriş Yap").click()
    element = self.driver.find_element(By.LINK_TEXT, "Giriş Yap")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.NAME, "email").send_keys("recepodemis6@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Rto1208279125")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".name")))
    self.driver.find_element(By.CSS_SELECTOR, ".p-0:nth-child(1)").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Profil Bilgileri")))
    self.driver.find_element(By.LINK_TEXT, "Profil Bilgileri").click()
    self.driver.find_element(By.LINK_TEXT, "Eğitim Hayatım").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".btn-primary")))
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    assert self.driver.find_element(By.CSS_SELECTOR, ".col-12:nth-child(5) > .text-danger:nth-child(3)").text == "Doldurulması zorunlu alan*"
    self.driver.close()
  
