# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestControlchatbot():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_controlchatbot(self):
    self.driver.get("https://tobeto.com/")
    self.driver.set_window_size(1680, 953)
    self.driver.switch_to.frame(2)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".exw-open-launcher__container")))
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(3)
    self.driver.find_element(By.CSS_SELECTOR, "strong").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(1)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "message")))
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "input")))
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("tobeto test")
    self.driver.find_element(By.CSS_SELECTOR, ".exw-inline-response-input-container > svg").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".exw-reply:nth-child(1)")))
    self.driver.find_element(By.CSS_SELECTOR, ".exw-reply:nth-child(1)").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".exw-reply:nth-child(1)")))
    self.driver.find_element(By.CSS_SELECTOR, ".exw-reply:nth-child(3)").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".exw-reply:nth-child(1)")))
    self.driver.close()
  
